services:
  - type: web
    name: queen-elizabeth-academy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: https://nuqvqeynhssipmcmebxb.supabase.co
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: sb_secret_lyhSTSksrgvfStyVmAjwZw_KmG1ltjc
