services:
  - type: web
    name: queen-elizabeth-academy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: https://nuqvqeynhssipmcmebxb.supabase.co/rest/v1/
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: sb_publishable_WjBgPoBpB1ONRrQh_JSucA_X_cCiDZY
